<h2><i class="fas fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form method="post" action="<?=$requestUrl?>/user/login/">
    <fieldset>
        <legend>Informations d'authentification</legend>
        <label for="email">E-mail :</label>
        <input type="email" name="email" id="email" required><br>

        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password" required>
    </fieldset>
    <input type="submit" class="button" value="Connexion" name="connect" id="connect">
    <a href="<?=$requestUrl?>/user/login" class="button button-cancel">Annuler</a>
</form>