<h2><i class="fas fa-user"></i> Création d'un compte client</h2>

<form method="post" action="<?=$requestUrl?>/user/register/">
    <fieldset>
        <legend><i class="fas fa-book"></i> Identité et coordonnées</legend>
        <label for="name">Nom :</label>
        <input type="text" name="name" id="name" required><br>

        <label for="firstname">Prénom :</label>
        <input type="text" name="firstname" id="firstname" required><br>

        <label for="date">Date de naissance :</label>
        <input type="date" name="date" id="date" required><br>

        <label for="address">Adresse :</label>
        <input type="textarea" name="address" id="address" required><br>

        <label for="city">Ville :</label>
        <input type="text" name="city" id="city" required><br>

        <label for="zipcode">Code Postal :</label>
        <input type="text" name="zipcode" id="zipcode" required><br>

        <label for="country">Pays :</label>
        <input type="text" name="country" id="country" required><br>

        <label for="phone">Telephone :</label>
        <input type="tel" name="phone" id="phone" pattern="[0-9]{10}" required><br>

        <input type="timeStamp" name="timeStamp" id="timeStamp" style="display:none;">
    </fieldset>
    <fieldset>
        <legend><i class="fas fa-lock"></i> Informations d'authentification</legend>
        <label for="email">E-mail :</label>
        <input type="email" name="email" id="email" required><br>

        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password" required>
    </fieldset>
    <input type="submit" class="button" value="Créer le compte" name="submit" id="submit">
    <a href="<?=$requestUrl?>/user/register" class="button button-cancel">Annuler</a>
</form>