<!-- Message de notification -->

<!-- Liste des aliments -->
<table class="generic-table meal-list">

    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php foreach($meals as $m):?>
        <tr>
            <td><img src="<?=$wwwUrl?>/images/meals/<?=$m['Photo']?>"></td>
            <td>
            <p><?=$m['Name']?></p>
            <p><?=$m['Description']?></p>
            </td>
            <td><?=$m['SalePrice']?> &euro;</td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>