<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Restaurant</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
<!-- Interface utilisateur -->
    <nav class="user-interface">
        <ul class="link-list">
            <!-- Code HTML/PHP à écrire -->
            <?php if(isset($_SESSION['user'])): ?>
            <div id="buttonsBloc">
                <?php if($_SESSION['user']['Admin'] == 1): ?>
                    <a href="<?=$requestUrl?>/user/admin" class="button">Admin</a>
                    <a href="<?=$requestUrl?>/user/users" class="button">Utilisateurs</a>
                    <a href="<?=$requestUrl?>/user/meal" class="button">Meal</a>
                <?php endif; ?>
                <a href="<?=$requestUrl?>/user/update" class="button">Mon compte</a>
                <a href="<?=$requestUrl?>/user/book" class="button">Réserver</a>
                <a href="<?=$requestUrl?>/user/order" class="button">Commander</a>
                <div>
                    <li>Bonjour <span><?= $_SESSION['user']['FirstName'] ?></span> !</li>
                    <form method="post" action="<?=$requestUrl?>/user/logout/" style="display:inline-block;">
                        <button class="button">Déconnexion</button>
                    </form>
                </div>
            </div>
            <?php else: ?>
            <div id="buttonsBloc">
                <a href="<?=$requestUrl?>/user/register" class="button">Creer un compte</a>
                <a href="<?=$requestUrl?>/user/login" class="button">Connexion</a>
            </div>
            <?php endif; ?>
        </ul>
    </nav>
</header>

<main class="container">
    <h1>
        <a href="<?= $requestUrl ?>">Restaurant - Made in France !</a>
    </h1>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script>
    const ServerConfig = {
        requestUrl: '<?= $requestUrl ?>',
        wwwUrl: '<?= $wwwUrl ?>'
    };
</script>
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>